config/routes.rb
Facebook::Application.routes.draw do
  get "home/index"

match "/auth/:provider/callback" => "sessions#create"
match "/signout" => "sessions#destroy", :as => :signout
resources :numbers
resources :home

  root :to => "home#index"

end

app/models/number.rb
class Number < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["user_info"]["name"]
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :current_user
  
  def index
  end 
  
  def create
    @name = params[:name]
    @user = User.where(:name => @name )
    current_user.information = params[:information]
    if current_user.save!
      render :json => {:sucess => true, :reason => "your information was saved!"}, :status => 200
    else
      render :json => {:success => false, :reason => "your infomration wasn't read"}, :status => 400
    end
  end
  
    
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  def create
    @num = Number.new(params[:number])
    if @num.save
      render :json => {
      :success => true # :location => url_for(:controller => "campaigns", :action => "management", :store_id => @camp.store_id), :campaign => @camp.id
      }, :status => 200
    else
      logger.debug('i am here')
      render :json => {
      :success => false# , :reason => @camp.errors.full_messages
      }, :status => 300    
    end
  end
  
  def index
    render :json => (Number.all)    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def create
  auth = request.env["omniauth.auth"]
  user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
  session[:user_id] = user.id
  redirect_to root_url, :notice => "Signed in!"
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Signed out!"
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/numbers_helper.rb
module NumbersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<html>
<body>
<h1>Hey! You can sign in with facebook!!</h1>
<p>What who are you?</p>
<div id="styleme">
<p> Style me </p>	
</div>
<input type="text" id="nums">
<input type="button" id="face" value="push me"><br>
<input type="button" id="display" value="display last input"><br>
<div id="showing">	
</div>
<div id="video">
	
</div>
<!-- <%if current_user%>
	<%if current_user.name == "Jackie Gushue"%>
	<video id="jackievid" src="/videos/forjackie.mp4" controls="controls" onclick="this.play();">This doesn't work</video>
	<%else%>
	<video id="myvid" src="/videos/testmovie.mp4" controls="controls">This doesn't work</video>
	<%end%>
<%else%>
	<div>please sign in</div>
<%end%>       -->

<%if current_user%>
	<input type="hidden" id="UserName" value="<%=current_user.name%>">
	<%if current_user.name == "Nikka Ghalili"%>
	<h3>Welcome Nikka!</h3>
    	<p>Please input your info</p>
			<textarea id="infos"></textarea>
			<button id="infosubmit">submit</button>
	<%else%>
	<div>You are logged in!! But you aren't nikka...</div>
	<%end%>
<%end%>
</body>
</html>


<script type="text/javascript" charset="utf-8">

//var PopArr = null;
	$("#face").click(function(){
		$.ajax({
			url: "/numbers/",
			type: "POST",
			data: {
				"remote" : true,
				"number" : {
					"calc": $("#nums").val()	
				},
				
			},
			success: function() {
				alert("it worked!!");
			},
			error: function(jqXHR) {
				console.log(jqXHR);
			}
			
		});
	});
	
	$("#display").click(function(){
		$.ajax({
			url: "/numbers/",
			type: "GET",
			success: function(data) {
				// for (i in data) {
				// 	console.log(data[i]);
				// 	PopArr[i] = data[i].calc; 				
				// }
				//PopArr = data;  
				// console.log(PopArr);
				var l = data.length - 1;
				$("#showing").text(data[l].number.calc);
 
			},
		});
	});
	
	$("#infosubmit").click(function(){
		$.ajax({
			url: "/home/",
			type: "POST",
			data: {
				"remote" : true,
				"user" : {
					"name" : $("#UserName").val,
					"information" : $("#infos").val()
				},
			},
			
			success: function(data) {
				console.log(data);
			},
			error: function(data) {
				console.log(data);
			}
		});
	});
</script>

<style type="text/css" media="screen">
	#styleme {
		float: right;
	}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" %>
	<title>Check it out!! you can sign in with Facebook! </title>
</head>
<body>

<div id="container">
	<div id="user_nav">
    <% if current_user %>
        Welcome <%= current_user.name %>!
        <%= link_to "Sign Out", signout_path %>
    <% else %>
        <%= link_to "Sign in with Facebook son", "http://nikkaghalili.com/auth/facebook" %>
    <% end %>
  </div>
</div>
<%=yield%>
</body>
</html>